=== malaklouka/tache_software_xml/softwareDTD.dtd
<!ELEMENT collection (header,software+,criteria,utils,references)>
<!ELEMENT header (introduction)>
<!ELEMENT introduction (#PCDATA)*>
<!ELEMENT software (name,icon,screenshots,description,version,developer,requirements,download,website,features)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT icon EMPTY>
<!ATTLIST icon href CDATA #REQUIRED
			   width CDATA #REQUIRED
			   height CDATA #REQUIRED>
<!ELEMENT screenshots (screenshot+)>
<!ELEMENT screenshot EMPTY>
<!ATTLIST screenshot mime (png|jpeg|gif) #REQUIRED
					 href CDATA #REQUIRED
					 width CDATA #REQUIRED
					 height CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)*>
<!ELEMENT version (#PCDATA)*>
<!ELEMENT developer (#PCDATA)*>
<!ELEMENT requirements (os)>
<!ELEMENT os (#PCDATA)>
<!ELEMENT download (link+)>
<!ELEMENT link EMPTY>
<!ATTLIST link os CDATA #REQUIRED
			   href CDATA #REQUIRED>
<!ELEMENT website EMPTY>
<!ATTLIST website url CDATA #REQUIRED>
<!ELEMENT features (feature)+>
<!ATTLIST feature title CDATA #REQUIRED>
<!ELEMENT feature (exist)+>
<!ELEMENT exist (#PCDATA)*>
<!ELEMENT criteria (item1)+>
<!ELEMENT item1 EMPTY>
<!ATTLIST item1 title CDATA #REQUIRED>
<!ELEMENT utils (green,red)>
<!ELEMENT green EMPTY>
<!ELEMENT red EMPTY>
<!ATTLIST green href CDATA #REQUIRED
				width CDATA #REQUIRED
				height CDATA #REQUIRED>
<!ATTLIST red href CDATA #REQUIRED
		  	  width CDATA #REQUIRED	
		      height CDATA #REQUIRED>
<!ELEMENT references (ref)+>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref software CDATA #REQUIRED>

=== malaklouka/tache_software_xml/software.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE collection SYSTEM "softwareDTD.dtd">
<?xml-stylesheet type="text/xsl" href="software_xsl.xsl"?>
<collection>
	<header>
		<introduction>
			Deep learning helps researchers analyze medical data to treat diseases. It enhances doctors’ ability to analyze medical images. It’s advancing the future of personalized medicine. It even helps the blind “see.”“Deep learning is revolutionizing a wide range of scientific fields,” said Jensen Huang, NVIDIA CEO and co-founder. “There could be no more important application of this new capability than improving patient care.
		</introduction>
	</header>

	<software>
		<name>Skin cancer</name>
		<icon href="icons/skin.jpg" width="60" height="60" />
	<screenshots>
			<screenshot mime="png" href="icons/skin.jpg" width="320"
				height="200" />
			<screenshot mime="png" href="icons/skin.jpg" width="320"
				height="200" />
		</screenshots>
		<description>
			Skin cancer, the most common human malignancy is primarily diagnosed visually, beginning with an initial clinical screening and followed potentially by dermoscopic analysis, a biopsy and histopathological examination. Automated classification of skin lesions using images is a challenging task owing to the fine-grained variability in the appearance of skin lesions. Deep convolutional neural networks (CNNs) show potential for general and highly variable tasks across many fine-grained object categories6,7,8,9,10,11. Here we demonstrate classification of skin lesions using a single CNN, trained end-to-end from images directly, using only pixels and disease labels as inputs. We train a CNN using a dataset of 129,450 clinical images two orders of magnitude larger than previous datasets12 consisting of 2,032 different diseases. We test its performance against 21 board-certified dermatologists on biopsy-proven clinical images with two critical binary classification use cases: keratinocyte carcinomas versus benign seborrheic keratoses; and malignant melanomas versus benign nevi.
The first case represents the identification of the most common cancers, the second represents the identification of the deadliest skin cancer. 
		</description>
	
		
	</software>

	<software>
		<name>Alzeihmer</name>
		<icon href="icons/alz.png" width="60" height="60" />
		<screenshots>
			<screenshot mime="png" href="icons/alz.png" width="320"
				height="200" />
			<screenshot mime="png" href="icons/alz.png" width="320"
				height="200" />
		</screenshots>
		<description>
			The accurate diagnosis of Alzheimer's disease (AD) plays a significant role in patient care, especially at the early stage, because the consciousness of the severity and the progression risks allows the patients to take prevention measures before irreversible brain damages are shaped.
Although many studies have applied machine learning methods for computer aided diagnosis (CAD) of AD recently, a bottleneck of the diagnosis performance was shown in most of the existing researches, mainly due to the congenital limitations of the chosen learning models.
In this study, we design a deep learning architecture, which contains stacked autoencoders and a softmax output layer, to overcome the bottleneck and aid the diagnosis of AD and its prodromal stage, Mild Cognitive Impairment (MCI).
Compared to the previous workflows, our method is capable of analyzing multiple classes in one setting, and requires less labeled training samples and minimal domain prior knowledge. 
A significant performance gain on classification of all diagnosis groups was achieved in our experiments.
		</description>
		
	</software>

	<software>
		<name>leukemia</name>
		<icon href="icons/lk.png" width="60" height="60" />
		<screenshots>
			<screenshot mime="png" href="icons/lk.png"
				width="341" height="170" />
			<screenshot mime="png" href="icons/lk.png"
				width="341" height="170" />
		</screenshots>
		<description>
			Acute Leukemia is a life-threatening disease common both in children and adults that can lead to death if left untreated. Acute Lymphoblastic Leukemia (ALL) spreads out in children's bodies rapidly and takes the life within a few weeks. To diagnose ALL, the hematologists perform blood and bone marrow examination. Manual blood testing techniques that have been used since long time are often slow and come out with the less accurate diagnosis. This work improves the diagnosis of ALL with a computer aided system, which yields accurate result by using image processing and deep learning techniques. This research proposed a method for the classification of ALL into its subtypes and reactive bone marrow (normal) in stained bone marrow images.
A robust segmentation and deep learning techniques with the convolutional neural network are used to train the model on the bone marrow images to achieve accurate classification results.
Experimental results thus obtained and compared with the results of other classifiers Naïve Bayesian, KNN, and SVM. Experimental results reveal that the proposed method achieved 97.78% accuracy.
The obtained results exhibit that the proposed approach could be used as a tool to diagnose Acute Lymphoblastic Leukemia and its subtypes that will definitely assist pathologists.
		</description>
		
	</software>


	<!--<software> <name>Navegatium DICOM Viewer</name> <icon href="icons/navegatium_60.png" 
		width="60" height="60"/> <screenshots> <screenshot mime="image/jpeg" href="screenshots/navegatium1.jpg" 
		width="256" height="200"/> <screenshot mime="image/jpeg" href="screenshots/navegatium2.jpg" 
		width="320" height="202"/> </screenshots> <description> Navegatium est le 
		visualiseur DICOM qui ronge le monde des applications dans le domaine médical. 
		Avec une approche innovante sur le marché, il peut être acquis gratuitement 
		via Windows Store . Il est considéré par de nombreux utilisateurs comme le 
		visualiseur médical le plus facile à utiliser sur le marché, il dispose d'une 
		interface permettant à chaque médecin de consulter un logiciel médical, sans 
		oublier la fonctionnalité et les fonctionnalités puissantes à explorer et 
		manipuler des études DICOM (fichiers .dcm). compliqué. Le Navegatium DICOM 
		Viewer est également intégré au PACS (système d' archivage et de communication 
		d' images ) pour les hôpitaux, les cliniques et les centres de recherche, 
		permettant aux médecins, radiologues, les pathologistes et les chercheurs 
		consultent et stockent leurs études et l'imagerie médicale dans leurs institutions 
		de travail. </description> <version>1.10</version> <developer>NAVEGATIUM</developer> 
		<requirements> <os>Windows 10 / 8.1</os> </requirements> <website url="http://www.navegatium.com/dicom-viewer"/> 
		<features> <feature title="Construction 3D"> <exist>true</exist> </feature> 
		<feature title="Construction 4D/5D"> <exist>true</exist> </feature> <feature 
		title="Traitement d’imagerie de flux sanguin (extraction des mesures pour 
		le flux)"> <exist>true</exist> </feature> <feature title="Nombre de patient 
		accepté/capacité d’adaptabilité"> <exist>true</exist> </feature> <feature 
		title="Mesures locaux/filtres usuelles"> <exist>true</exist> </feature> <feature 
		title="Gestion des plugin"> <exist>true</exist> </feature> <feature title="Outils 
		de diffusion (DTI,DKI) /Imagerie DWI"> <exist>true</exist> </feature> </features> 
		</software> -->
	<software>
		<name>Cardiology</name>
		<icon href="icons/card.png" width="60" height="60" />
		<screenshots>
			<screenshot mime="png" href="icons/card.png"
				width="341" height="213" />
			<screenshot mime="png" href="icons/card.png"
				width="341" height="213" />
		</screenshots>
		<description>
			Our intention is to produce a computer aided diagnosis tool to assist clinicians in diagnosing heart disease and planning its treatment using motion and/or deformation information. The tool will be based on the latest deep learning techniques, and the application of deep learning to cardiac motion analysis represents the first main novelty of this project. The second novelty lies in the explanatory power of the tool. 
			By offering clear and intuitive information that can help to generate explanations for its outputs it is hoped that one of the most significant obstacles to the clinical translation of machine learning techniques in medicine can be overcome.
		</description>
		
			
	</software>

	<software>
		<name>Robotic surgery</name>
		<icon href="icons/r.png" width="60" height="60" />
		<screenshots>
			<screenshot mime="jpeg" href="icons/r.png"
				width="320" height="187" />
			<screenshot mime="jpeg" href="icons/r.png"
				width="320" height="187" />
		</screenshots>
		<description>With the advent of robot assisted surgery, the role of data driven approaches to integrate statistics and machine learning is growing rapidly with prominent interests in objective surgical skill assessment.
